README.md
project.clj
src/muuntaja/core.clj
src/muuntaja/middleware.clj
src/muuntaja/parse.clj
test/muuntaja/core_perf_test.clj
test/muuntaja/core_test.clj
test/muuntaja/middleware_test.clj
test/muuntaja/parse_test.clj

* request charset negotiation (implemented, not effective)
* response format negotiation
* accept negotiation
* accept-charset negotiation (not effective)
* 200ns-500ns extra latency if both request & response negotiation is on
* cleanup internals
* **TODO**
* use the negotiated charset in decode/encode

Memoized negotiations

---

README.md
project.clj
src/muuntaja/core.clj
src/muuntaja/interceptor.clj
src/muuntaja/middleware.clj
test/muuntaja/core_perf_test.clj
test/muuntaja/core_test.clj
test/muuntaja/middleware_test.clj
test/muuntaja/ring_json/json_test.clj
test/muuntaja/ring_middleware/format_params_test.clj
test/muuntaja/ring_middleware/format_response_test.clj
test/muuntaja/ring_middleware/format_test.clj

* remove type aliases (e.g. `:json`) from public apis, just content-types (e.g. `"application/json"`) now.
* add creation time runtime assertions for ill usage
* cleanup examples

Content type 4 public api

---

project.clj
src/muuntaja/formats.clj
test/muuntaja/core_perf_test.clj
test/muuntaja/core_test.clj
test/muuntaja/formats_perf_test.clj
test/muuntaja/middleware_test.clj
test/muuntaja/ring_json/json_test.clj
test/muuntaja/ring_middleware/format_response_test.clj
test/muuntaja/ring_middleware/format_test.clj

Instead of returning JSON, YAML or EDN String, all encode-functions return now an InputStream. Added tests to verify that via `ring.core.protocols.StreamableResponseBody`, stream handling is much more efficient (2-3 better perf). Also, enables the response charset to be set.

Encode returns always a Stream

---

README.md
src/muuntaja/core.clj
src/muuntaja/formats.clj
src/muuntaja/middleware.clj
test/muuntaja/middleware_test.clj

Started to integrate into compojure.api. Noticed that the encode & decode can't be done in the same steps if one want's to do the exception handling in a central place:
* if a request parsing fails, an exception is thrown (and caught in a separate mw). How does this mw know how to render the format exception in the negotiated format?
* solution: separate negotiation from request decode. New mws to enable running those in separate stages:
```clj
;; with defaults
(def m (m/create))
;; still works, bundles all together
(-> app (middleware/wrap-format m))
;; can be run as separate steps
(-> app
(middleware/wrap-format-request m)
(middleware/wrap-format-response m)
(middleware/wrap-format-negotiate m))
```

Separate negotiation

---

CHANGELOG.md
README.md
src/clj/muuntaja/core.clj
src/clj/muuntaja/protocols.clj
test/muuntaja/core_test.clj

is the option name good? Should be something more explicit?
* `:allow-empty-input?`
* `:allow-empty-body-on-decode?`
* `:allow-nil-on-decode?`

optionally allow empty input on decode, fixes #33

---

CHANGELOG.md
README.md
project.clj
src/clj/muuntaja/core.clj
src/clj/muuntaja/protocols.clj
test/muuntaja/core_test.clj

Safe-guard for `nil` input(stream) in all cases.

Handle nil-input (fixes #41)

---

CHANGELOG.md
README.md
src/clj/muuntaja/core.clj
src/clj/muuntaja/format/edn.clj
src/clj/muuntaja/format/json.clj
src/clj/muuntaja/format/msgpack.clj
src/clj/muuntaja/format/transit.clj
src/clj/muuntaja/format/yaml.clj
test/muuntaja/core_perf_test.clj
test/muuntaja/core_test.clj

Remove the manual enconding by default. It's mostly  not needed. Guide on wiki how to enable that back.

Disable manual encoding of record by default

---

src/clj/muuntaja/format/jsonista.clj
test/muuntaja/core_test.clj

Closes https://github.com/metosin/muuntaja/issues/24, but depends on https://github.com/metosin/jsonista/pull/6.

Support defining decoder charset for Jsonista

---

CHANGELOG.md
project.clj

* depend directly on `[com.fasterxml.jackson.core/jackson-core "2.9.3"]` to avoid transitive version clashes with Cheshire & Jsonista.
* update deps

Fix deps conflicts

---

CHANGELOG.md
project.clj
src/clj/muuntaja/core.clj
src/clj/muuntaja/format/jsonista.clj
src/clj/muuntaja/interceptor.clj
src/clj/muuntaja/middleware.clj
src/clj/muuntaja/parse.clj
src/clj/muuntaja/records.clj
test/muuntaja/core_perf_test.clj
test/muuntaja/core_test.clj
test/muuntaja/formats_perf_test.clj

* Fixes #59 
* Optimized `negotiate-and-format-request` (less hash-lookups)
* Optimized path for UTF-8 with Jsonista
* +20% better e2e throughput with middleware (Jsonista)

Re-implement Muuntaja as Protocol

---

.gitignore
CONTRIBUTING.md
README.md
doc/Configuration.md
doc/Creating-new-formats.md
doc/Differences-to-existing-formatters.md
doc/Performance.md
doc/With-Ring.md
doc/cljdoc.edn

This PR sets up muuntaja for [cljdoc](https://cljdoc.xyz). In summary this means moving the wiki into the repo and adding `doc/cljdoc.edn`. 
I fixed all links and added titles to all files and added a cljdoc badge to the Readme that points users to the most recent release on cljdoc.
Updating [existing docs](https://cljdoc.xyz/d/metosin/muuntaja/0.6.0-alpha1/doc/readme) isn't possible at this point so if this gets merged there will need to be a new release. (SNAPSHOT builds always use `master` as git revision.)
I hope this is useful 🙂

Setup cljdoc

---

modules/muuntaja/src/muuntaja/core.clj
test/muuntaja/core_test.clj

#86
Add 2 arity versions of `encode` and `decode` that use the default Muuntaja `instance`
Added some basic tests for the 2 arity cases.
The contribution guide mentions `lein midje` but that's not a known task -- I tested with `lein test`.
Since 3 arity is already taken, the default instance variants can't take a charset option.

Arity 2 encode/decode

---

README.md

Since last October, [the domain has been migrated to cljdoc.org](https://github.com/cljdoc/cljdoc/blob/e8f01d6865cfa123bf792144a1c1908c60daeb77/doc/updates/0006-cljdoc-october.md#things-that-have-have-been-shipped-in-october). The updated link points to the latest version of the documentation, which is https://cljdoc.org/d/metosin/muuntaja/0.6.4/doc/readme as today.

Update README - change cljdoc.xyz domain to cljdoc.org

---

README.md

Hi there !
I had a hard time trying to change the date format of my generated `json`.
I could't find any reference for the `date-format `option so I just wanted to add it here.
I hope it'll be usefull.

add date-format configuration example

---

modules/muuntaja-cheshire/project.clj
modules/muuntaja-msgpack/project.clj
modules/muuntaja-yaml/project.clj
modules/muuntaja/project.clj

when running `lein repl` from the muuntaja module there was the following error
```sh
Error: Could not find or load main class clojure.main
Caused by: java.lang.ClassNotFoundException: clojure.main
Subprocess failed (exit code: 1)
```
This error means that the Clojure jar was not in the classpath. Inheriting the :dev profile as documented by [lein-parent](https://github.com/achin/lein-parent#usage) fixes the problem.
Fixes #108

modules: Inherit :dev profile

---

README.md
modules/muuntaja/project.clj
modules/muuntaja/src/muuntaja/core.clj
modules/muuntaja/src/muuntaja/format/form.clj
project.clj
test/muuntaja/core_test.clj

This implements encoding/decoding for the `application/x-www-form-urlencoded` media-type which is the default format sent by browsers when submitting HTML forms using the POSTmethod.
The implementation relies on the `ring.util.codec` library to perform both the encoding and decoding. This is the same library that is used by the `ring.middleware.params` alternative solution for handling both query params and body params encoded with the `application/x-www-form-urlencoded` media-type.
This fixes #27.

Support ‘application/x-www-form-urlencoded’

---

.gitignore
project.clj

There is no java sources to compile and by default `:dependencies` is already empty.

Remove unneeded 'project.clj' configuration

---

README.md

The application/x-www-form-urlencoded abstraction was moved into own module in #113 
But the README still states it as part of core abstractions.

Remove application/x-www-form-urlencoded from core abstractions

---

modules/muuntaja/src/muuntaja/core.clj
test/muuntaja/core_test.clj

Fix decode-response-body fails on falsy body content

---

CONTRIBUTING.md
modules/muuntaja-charred/project.clj
modules/muuntaja-charred/src/muuntaja/format/charred.clj
project.clj
scripts/lein-modules
test/muuntaja/core_test.clj

This PR adds [charred](https://github.com/cnuernber/charred) as a JSON encode/decoder module for muuntaja, like cheshire.
The code comes from a private project that uses muuntaja + reitit.
Open to suggestions for how to test and build it locally in the context of this repo, as well as any change requests.

Add charred json formatter module
